name = "subconverter-worker"
main = "worker.js"
compatibility_date = "2024-04-01"

# Rules for building/bundling
# Wrangler automatically handles .wasm files if imported from .js

[observability]
enabled = true
